version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify the desired Node.js version (e.g., Node.js 14.x)
    commands:
      - echo "Installing NPM dependencies..."
      - cd backend
      - npm install
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Build started on $(date)"
  post_build:
    commands:
      - echo "Post-build phase..."

artifacts:
  files:
    - '**/*'
  base-directory: 'backend'  # This should be set to the directory containing your package.json and node_modules
