version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - cd backend
      - npm install
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Copying files to the build directory"
      - mkdir -p build
      - cp -R $(ls | grep -v 'build') build/
      - echo "Files copied to build directory:"
      - ls -l build

artifacts:
  files:
    - '**/*'
  base-directory: 'backend/build'
  discard-paths: yes