version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - cd backend
      - npm install
      - echo "Listing backend directory after npm install:"
      - ls -l
  pre_build:
    commands:
      - echo "Pre-build phase..."
      # Add any pre-build commands here if necessary
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "No additional build commands required"
  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Zipping the application..."
      - zip -r ../backend.zip .
      - echo "Listing contents of the zip file:"
      - unzip -l ../backend.zip
      # Add any post-build commands here if necessary

artifacts:
  files:
    - backend.zip
  base-directory: 'backend' # This should be set to the directory containing your package.json and node_modules
  discard-paths: yes
