version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - cd backend
      - npm install
      - echo "Listing backend directory after npm install:"
      - ls -l
  pre_build:
    commands:
      - echo "Pre-build phase..."
      # Add any pre-build commands here if necessary
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "No additional build commands required"
  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Zipping the application..."
      - cd ..  # Navigate back to the root directory
      - zip -r backend.zip backend/  # Zip the backend directory
      - echo "Listing contents of the root directory:"
      - ls -l  # List the contents to verify the zip file creation

artifacts:
  files:
    - backend.zip
  base-directory: '.'  # Set to the root directory where backend.zip is located
  discard-paths: yes
