version: 0.2

phases:
  install:
    commands:
      - echo "Installing NPM dependencies..."
      - cd backend
      - npm install
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Build started on $(date)"
  post_build:
    commands:
      - echo "Post-build phase..."
      - cd ..  # Go back to the root directory
      - zip -r backend.zip backend/  # Create backend.zip from the backend directory

artifacts:
  files:
    - backend.zip
  discard-paths: yes
